apiVersion: v1
kind: ConfigMap # need to create the config map first, if any other references it.
metadata:
  name: mongodb-configmap
data:
  database_url: mongodb-service # add the name of the service 